name: Unit Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.3

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: ng test ngx-expandable-tree-list --watch=false --browsers=ChromeHeadless
